mod numbers;
mod variables;
mod char_bool_unit;
mod statements;
mod functions;
mod ownership;
mod borrowing;
mod string;
mod array;
mod slice;
mod tuple;
mod struct_f;
mod enum_f;
mod flow_control;
mod pattern_match;
mod method;
mod generic;
mod traits;
mod objtraits;
mod associated_types;
mod collection_string;
mod collection_vector;
mod collection_hashmaps;
mod type_conversion;
mod panic;
mod result;
mod documentation;

fn main() {
    variables::variables_ex();
    println!();
    numbers::numbers_ex();
    println!();
    char_bool_unit::char_bool_unit_ex();
    println!();
    statements::statements_ex();
    println!();
    functions::functions_ex();
    println!();
    ownership::ownership_ex();
    println!();
    borrowing::borrowing_ex();
    println!();
    string::string_ex();
    println!();
    array::array_ex();
    println!();
    slice::slice_ex();
    println!();
    tuple::tuple_ex();
    println!();
    struct_f::struct_ex();
    println!();
    enum_f::enum_ex();
    println!();
    flow_control::flow_control_ex();
    println!();
    pattern_match::pattern_match_ex();
    println!();
    method::method_ex();
    println!();
    generic::generic_ex();
    println!();
    traits::traits_ex();
    println!();
    objtraits::objtraits_ex();
    println!();
    associated_types::associated_types_ex();
    println!();
    collection_string::collection_string_ex();
    println!();
    collection_vector::collection_vector_ex();
    println!();
    collection_hashmaps::collection_hashmaps_ex();
    println!();
    type_conversion::type_conversion_ex();
    println!();
    panic::panic_ex();
    println!();
    result::result_ex();
    println!();
    documentation::documentation_ex();
}
